name: mechine_test
version: 1.0.0+1
publish_to: none
description: A new Flutter project For Mechine Test For Trogon
environment: 
  sdk: '>=3.4.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  google_fonts: 6.1.0
  dio: ^5.4.3+1
  dotted_border: ^2.1.0

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - asset/png/

